import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Typewriter from 'typewriter-effect';
import { IoClose } from 'react-icons/io5';
import { AiFillDelete, AiFillFileAdd, AiOutlineClose, AiOutlineCloseCircle } from 'react-icons/ai';

export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='min-h-screen max-w-full flex font-mono font-extralight'>
        <div className='w-1/2 bg-yellow-100 p-12 flex flex-col gap-3 justify-center  text-2xl relative max-md:hidden'>
          <div className='flex justify-between items-center gap-3 mb-5 pb-3 border-b-2 border-zinc-900'>
            <input type={'search'} className='bg-transparent text-3xl font-bold w-full focus:outline-none ' placeholder='Type your plan here...' />
            <div className='flex gap-3'>
              <AiFillFileAdd className='text-orange-400' />
            </div>
          </div>
          <div className='text-2xl w-full flex justify-between items-center gap-3'>
            <div className='flex justify-start gap-3 w-80'>
              <input type={'checkbox'} />
              <Typewriter options={{
                strings: ['Buy Apple', 'Buy Potato'],
                autoStart: true,
                loop: true,
              }} />
            </div>
            <AiFillDelete className='text-orange-400' />
          </div>
          <div className='text-2xl w-full flex justify-between items-center gap-3'>
            <div className='flex justify-start gap-3 w-80'>
              <input type={'checkbox'} />
              <Typewriter options={{
                strings: ['Be Nice', 'Be Creative'],
                autoStart: true,
                loop: true,
              }} />
            </div>
            <AiFillDelete className='text-orange-400' />
          </div>
          <div className='text-2xl w-full flex justify-between items-center gap-3'>
            <div className='flex justify-start gap-3 w-80'>
              <input type={'checkbox'} checked />
              <p className='line-through'>Well Done!</p>
            </div>
            <AiFillDelete className='text-orange-400' />
          </div>
          <div className='text-2xl w-full flex justify-between items-center gap-3'>
            <div className='flex justify-start gap-3 w-80'>
              <input type={'checkbox'} checked />
              <p className='line-through'>Dont be Anger!</p>
            </div>
            <AiFillDelete className='text-orange-400' />
          </div>
          <div className='text-2xl w-full flex justify-between items-center gap-3'>
            <div className='flex justify-start gap-3 w-80'>
              <input type={'checkbox'} checked />
              <p className='line-through'>Im The Best!</p>
            </div>
            <AiFillDelete className='text-orange-400' />
          </div>
          <div className='absolute bottom-4 left-0 w-full flex justify-center'>
            <button className="inline-flex items-center py-2 px-4 text-sm font-medium text-gray-500 bg-white rounded-lg border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
              Prev
            </button>
            <button className="inline-flex items-center py-2 px-4 ml-3 text-sm font-medium text-gray-500 bg-white rounded-lg border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
              Next
            </button>
          </div>
        </div>
        {/* <audio src="/t1.mp3" loop="false" autostart="true" hidden="true"></audio> */}
        <div className='w-1/2 h-screen flex flex-col justify-center items-center gap-5 max-md:w-full'>
          <h1 className='text-7xl text-zinc-800 font-bold font-mono'>
            Todo App
          </h1>
          <h2 className='text-2xl font-mono font-thin'>Whats on your mind?</h2>
          <Link href='/auth' className='text-2xl text-sky-800 font-sans font-bold'>Login</Link>
        </div>
      </main>
    </div>
  )
}
